# Generated by Django 5.2.7 on 2025-12-06 12:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Envelopes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope_home',
            name='Created_At',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
