# Generated by Django 5.2.7 on 2026-01-31 07:03

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Envelopes', '0002_envelope_home_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='envelope_home',
            constraint=models.CheckConstraint(condition=models.Q(('Money_Allocated__gte', 0)), name='env_allocated_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='envelope_home',
            constraint=models.CheckConstraint(condition=models.Q(('Money_Spent__gte', 0)), name='env_spent_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='envelope_home',
            constraint=models.CheckConstraint(condition=models.Q(('Money_Remaining__gte', 0)), name='env_remaining_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='envelope_home',
            constraint=models.CheckConstraint(condition=models.Q(('Money_Spent__lte', models.F('Money_Allocated'))), name='env_spent_lte_allocated'),
        ),
        migrations.AddConstraint(
            model_name='envelope_home',
            constraint=models.CheckConstraint(condition=models.Q(('Money_Remaining__lte', models.F('Money_Allocated'))), name='env_remaining_lte_allocated'),
        ),
        migrations.AddConstraint(
            model_name='envelope_home',
            constraint=models.CheckConstraint(condition=models.Q(('Money_Remaining', django.db.models.expressions.CombinedExpression(models.F('Money_Allocated'), '-', models.F('Money_Spent')))), name='env_remaining_consistent'),
        ),
    ]
