# Generated by Django 5.2.7 on 2026-01-31 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Envelopes', '0003_envelope_home_env_allocated_gte_0_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='envelope_home',
            name='env_remaining_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='envelope_home',
            name='env_spent_lte_allocated',
        ),
        migrations.RemoveConstraint(
            model_name='envelope_home',
            name='env_remaining_lte_allocated',
        ),
    ]
