# Generated by Django 5.2.7 on 2026-02-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Envelopes', '0004_remove_envelope_home_env_remaining_gte_0_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envelope_home',
            name='Money_Allocated',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='envelope_home',
            name='Money_Remaining',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='envelope_home',
            name='Money_Spent',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
