# Generated by Django 5.2.7 on 2025-12-14 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Envelopes', '0002_envelope_home_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvelopeDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('Money_Spent', models.IntegerField()),
                ('Money_Remaining', models.IntegerField()),
                ('EnvelopeName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Envelopes.envelope_home')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
