# Generated by Django 5.2.7 on 2026-01-31 07:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvelopeDescription', '0002_envelopedescription_created_at'),
        ('Envelopes', '0003_envelope_home_env_allocated_gte_0_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='envelopedescription',
            constraint=models.CheckConstraint(condition=models.Q(('Money_Spent__gt', 0)), name='envdesc_spent_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='envelopedescription',
            constraint=models.CheckConstraint(condition=models.Q(('Money_Remaining__gte', 0)), name='envdesc_remaining_gte_0'),
        ),
    ]
