# Generated by Django 5.2.7 on 2026-01-31 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnvelopeDescription', '0003_envelopedescription_envdesc_spent_gt_0_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='envelopedescription',
            name='envdesc_remaining_gte_0',
        ),
    ]
