# Generated by Django 5.2.7 on 2026-02-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvelopeDescription', '0004_remove_envelopedescription_envdesc_remaining_gte_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envelopedescription',
            name='Money_Remaining',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='envelopedescription',
            name='Money_Spent',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
